export const ALLSUBCATEGORIES = "ALLSUBCATEGORIES"
export const ALLCOLORS = "ALLCOLORS"
export const ALLBRANDS = "ALLBRANDS"
export const ALLSIZES = "ALLSISEZ"
export const ALLCATEGORIES = "ALLCATEGORIES"
export const ALLPRODUCTS = "ALLPRODUCTS"

// export const ALLCATEGORIES = "ALLCATEGORIES"
// export const ALLSUBCATEGORIES = "ALLSUBCATEGORIES"
// export const ALLBRANDS = "ALLBRANDS"
// export const ALLSIZES = "ALLSIZES"
// export const ALLCOLORS = "ALLCOLORS"

export const SELECTEDCATEGORY = "SELECTEDCATEGORY"
