export const ALLSUBCATEGORIES = "ALLSUBCATEGORIES"
export const ALLCOLORS = "ALLCOLORS"
export const ALLBRANDS = "ALLBRANDS"
export const ALLSIZES = "ALLSISEZ"
export const ALLCATEGORIES = "ALLCATEGORIES"
export const ALLPRODUCTS = "ALLPRODUCTS"
export const SELECTEDCATEGORY = "SELECTEDCATEGORY"
export const CLEAN_DETAIL = 'CLEAN_DETAIL'
export const PRODUCTS_DETAIL = 'PRODUCTS_DETAIL'
export const PRODUCTS_FILTERED = 'PRODUCTS_FILTERED'

//provisional
export const COPY_ALLPRODUCTS = 'COPY_ALLPRODUCTS'